version: '3.8'

services:
  mariadb:
    image: mariadb:11.1.2-jammy
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: pulp-manager
      MARIADB_PASSWORD: pulp-manager
      MARIADB_ROOT_PASSWORD: my-root-password
      MARIADB_DATABASE: pulp_manager
    networks:
      - pulp-net

  redis:
    image: redis:latest
    networks:
      - pulp-net

  pulp-manager-api:
    build: .
    entrypoint: ["/bin/sh", "-c"]
    command: ["/usr/local/bin/pulp-manager -m && /usr/local/bin/pulp-manager -a --no-ssl --dev && /usr/local/bin/pulp-manager -w"]
    volumes:
      - .:/pulp_manager
    ports:
      - "8080:8000"
    environment:
      DB_HOSTNAME: mariadb
      DB_NAME: pulp_manager
      DB_USER: pulp-manager
      DB_PASSWORD: pulp-manager
      JWT_SECRET: test_secret
      PULP_MANAGER_CONFIG_PATH: /pulp_manager/local_config.ini
      PULP_SYNC_CONFIG_PATH: /pulp_manager/local_pulp_config.yml
      #PULP_MANAGER_SKIP_PARSER_CONFIG: 1
      Is_local: true
    depends_on:
      - mariadb
      - redis
    networks:
      - pulp-net
 
  pulp-python-worker:
    build: .
    entrypoint: ["/bin/sh", "-c"]
    command: ["/usr/local/bin/pulp-manager -w"]
    volumes:
      - .:/pulp_manager
    environment:
      DB_HOSTNAME: mariadb
      DB_NAME: pulp_manager
      DB_USER: pulp-manager
      DB_PASSWORD: pulp-manager
      JWT_SECRET: test_secret
      PULP_MANAGER_CONFIG_PATH: /pulp_manager/local_config.ini
      PULP_SYNC_CONFIG_PATH: /pulp_manager/local_pulp_config.yml
      #PULP_MANAGER_SKIP_PARSER_CONFIG: 1
      Is_local: true
    depends_on:
      - mariadb
      - redis
      - pulp-manager-api
    networks:
      - pulp-net

networks:
  pulp-net:
    external: true
