version: "3.8"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "./wait_db.sh  && coverage erase && make test  && make cover"
    restart: "no"
    environment:
      DB_HOSTNAME: db
      DB_NAME: pulp_manager
      DB_USER: pulp-manager
      DB_PASSWORD: pulp-manager
      PULP_MANAGER_SKIP_PARSER_CONFIG: 1
      PULP_MANAGER_CONFIG_PATH: /pulp_manager/local_config.ini
    depends_on:
      - db

  db:
    image: mariadb:11.1.2-jammy
    restart: "no"
    environment:
      MARIADB_USER: pulp-manager
      MARIADB_PASSWORD: pulp-manager
      MARIADB_ROOT_PASSWORD: my-root-password
      MARIADB_DATABASE: pulp_manager
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
