pulp_servers:
  pulp-web:8080:
    credentials: local
    repo_config_registration:
        schedule: "0,15,30,45 * * * *"
        max_runtime: "20m"
    repo_groups:
      external_repos:
        schedule: "00 13 * * *"
        max_concurrent_syncs: 2
        max_runtime: "6h"
    snapshot_support:
      max_concurrent_snapshots: 2


credentials:
  local:
    username: admin
    vault_service_account_mount: service-accounts # optional: Password is loaded from ini file.

repo_groups:
  external_repos:
    regex_include: "^ext"
