"""Adding internal worker id

Revision ID: 00db1cd3296a
Revises: e3d52c58c4d9
Create Date: 2023-10-23 10:42:51.317659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00db1cd3296a'
down_revision: Union[str, None] = 'e3d52c58c4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('worker_job_id', sa.String(length=256), nullable=True))
    op.create_index('tasks__index_worker_job_id', 'tasks', ['worker_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tasks__index_worker_job_id', table_name='tasks')
    op.drop_column('tasks', 'worker_job_id')
    # ### end Alembic commands ###
