"""adding datetime of repo health sync calculations

Revision ID: 0dae06fb4a3c
Revises: 00db1cd3296a
Create Date: 2023-10-24 14:36:23.303933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dae06fb4a3c'
down_revision: Union[str, None] = '00db1cd3296a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulp_server_repos', sa.Column('repo_sync_health_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pulp_servers', sa.Column('repo_sync_health_rollup_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulp_servers', 'repo_sync_health_rollup_date')
    op.drop_column('pulp_server_repos', 'repo_sync_health_date')
    # ### end Alembic commands ###
