"""support for repo registration

Revision ID: 1d9d4fd3f6fa
Revises: 28d3febd3e37
Create Date: 2023-12-11 13:15:11.960900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9d4fd3f6fa'
down_revision: Union[str, None] = '28d3febd3e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulp_servers', sa.Column('repo_config_registration_schedule', sa.String(length=256), nullable=True))
    op.add_column('pulp_servers', sa.Column('repo_config_registration_max_runtime', sa.String(length=10), nullable=True))
    op.add_column('pulp_servers', sa.Column('repo_config_registration_regex_include', sa.String(length=512), nullable=True))
    op.add_column('pulp_servers', sa.Column('repo_config_registration_regex_exclude', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulp_servers', 'repo_config_registration_regex_exclude')
    op.drop_column('pulp_servers', 'repo_config_registration_regex_include')
    op.drop_column('pulp_servers', 'repo_config_registration_max_runtime')
    op.drop_column('pulp_servers', 'repo_config_registration_schedule')
    # ### end Alembic commands ###
