"""adding support for pulp primary to pulp server repo group

Revision ID: 22c337db3f3e
Revises: 0dae06fb4a3c
Create Date: 2023-11-09 12:15:52.799484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c337db3f3e'
down_revision: Union[str, None] = '0dae06fb4a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulp_server_repo_groups', sa.Column('pulp_master_id', sa.Integer(), nullable=True))
    op.create_foreign_key('pulp_server_repo_groups__fk__pulp_master_id', 'pulp_server_repo_groups', 'pulp_servers', ['pulp_master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pulp_server_repo_groups__fk__pulp_master_id', 'pulp_server_repo_groups', type_='foreignkey')
    op.drop_column('pulp_server_repo_groups', 'pulp_master_id')
    # ### end Alembic commands ###
