"""add error string to task for issues where stage may not exist

Revision ID: 28d3febd3e37
Revises: 304a2180a31e
Create Date: 2023-11-21 12:49:31.487380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '28d3febd3e37'
down_revision: Union[str, None] = '304a2180a31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error_str', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error_str')
    # ### end Alembic commands ###
