"""adding support for snapshot config

Revision ID: 304a2180a31e
Revises: 22c337db3f3e
Create Date: 2023-11-21 09:53:12.210670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304a2180a31e'
down_revision: Union[str, None] = '22c337db3f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulp_servers', sa.Column('snapshot_supported', sa.Boolean(), nullable=True))
    op.add_column('pulp_servers', sa.Column('max_concurrent_snapshots', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulp_servers', 'max_concurrent_snapshots')
    op.drop_column('pulp_servers', 'snapshot_supported')
    # ### end Alembic commands ###
